http_addr:    "0.0.0.0:9680"

# https_addr:   "0.0.0.0:9681"

tunnel_addr:  "0.0.0.0:9690"

domain:       "xgrok-example.com"

# tls_crt:    "path/to/crt"

# tls_key:    "path/to/key"

use_auth:  false

authtokens:
    - aaa123abc
    - bbb456def

# pre_register:
#     - echo foo

# post_register:
#     - echo $XGROK_TUNNEL_URL

# pre_shutdown:
#     - echo $XGROK_TUNNEL_URL

# post_shutdown:
#     - echo $XGROK_TUNNEL_URL
